### ISSUE TITLE
Some weird stuff lol

### ISSUE THREAD

**Issue by sound-infinity** [Pakulichev/SL-MP#12]
![image](https://user-images.githubusercontent.com/39848886/101994742-a53c0d00-3c92-11eb-8c56-7b0000afee7e.png)

**Comment by Pakulichev** [comment]
This could be due to some kind of incompatibility: check your game. We recommend to use GTA: San Andres 1.0 US for this multiplayer without any additional content, only MoonLoader v.0.27-preview3 accepted. Also we can't guarantee working of pre-release versions since all preview versions were published only for tests. Sorry for that stuff.
